name: Node.js CI

on:
  push:
    branches:
      - main  # Change to 'master' if your default branch is named 'master'
  pull_request:
    branches:
      - main  # Change to 'master' if your default branch is named 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]  # You can specify more versions if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Run tests
      run: pnpm test

    - name: Report test results
      if: always()
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: 'junit.xml'
